platform:ios,'8.4'
inhibit_all_warnings!
pod 'Mantle','~>2.0'
pod ‘AFNetworking’,’~>2.6’
pod ‘MBProgressHUD’,’~>0.9’
pod ‘DJRefresh’,’~>1.0.5’
pod ‘KVOController’
pod ‘Masonry’
pod ‘CocoaLumberjack’
pod ‘FMDB’
pod ‘SDWebImage’