CREATE TABLE APP_CONFIGURATION (
VERSION varchar(15) NOT NULL,
BACKGROUND varchar(200),
ALERTSTATUS integer(2) NOT NULL DEFAULT(0)
);
CREATE TABLE BASE_CATEGORY (
CID varchar(36) PRIMARY KEY NOT NULL,
CNAME nvarchar(16) NOT NULL,
CCODE varchar(12) NOT NULL,
CPARENTCODE varchar(12) NOT NULL,
CSORT integer(4) NOT NULL DEFAULT(1),
CREATETIME varchar(128) NOT NULL,
CTYPE integer(2) NOT NULL DEFAULT(0),
ISVALID integer(2) NOT NULL DEFAULT(1),
CCOLOR char(2) NOT NULL DEFAULT('1')
);
CREATE UNIQUE INDEX BASECATEGORY_INDEX_CID ON BASE_CATEGORY (CID ASC);
CREATE TABLE BASE_FAMILY (
FID varchar(36) PRIMARY KEY NOT NULL,
FNAME varchar(36) NOT NULL,
FSORT integer(4) NOT NULL DEFAULT(0),
CREATETIME varchar NOT NULL,
ISEDIT char(1) NOT NULL DEFAULT('0')
);
CREATE UNIQUE INDEX BASEFAMILY_INDEX_FID ON BASE_FAMILY (FID ASC);
CREATE TABLE BUS_EXPENDITURE (
EID varchar(36) PRIMARY KEY NOT NULL,
EVALUE double(10) NOT NULL DEFAULT(0),
CID varchar,
FID varchar,
CREATETIME varchar NOT NULL,
EYEAR varchar(4) NOT NULL,
EMONTH varchar(6) NOT NULL,
EDAY varchar(8) NOT NULL,
IMARK nvarchar(36),
PID varchar(36),
FOREIGN KEY (CID) REFERENCES BASE_CATEGORY (CID) ON DELETE SET NULL,
FOREIGN KEY (FID) REFERENCES BASE_FAMILY (FID) ON DELETE SET NULL,
FOREIGN KEY (PID) REFERENCES BASE_PACKAGE (PID) ON DELETE SET NULL
);
CREATE UNIQUE INDEX BUSEXPENDITURE_INDEX_EID ON BUS_EXPENDITURE (EID ASC);
CREATE TABLE BUS_INCOME (
IID varchar(36) PRIMARY KEY NOT NULL,
CID varchar,
FID varchar,
IVALUE double(10) NOT NULL DEFAULT(0),
CREATETIME varchar NOT NULL,
IYEAR varchar(4) NOT NULL,
IMONTH varchar(6) NOT NULL,
IDAY varchar(8),
IMARK nvarchar(36),
PID varchar(36),
FOREIGN KEY (CID) REFERENCES BASE_CATEGORY (CID) ON DELETE SET NULL,
FOREIGN KEY (FID) REFERENCES BASE_FAMILY (FID) ON DELETE SET NULL,
FOREIGN KEY (PID) REFERENCES BASE_PACKAGE (PID) ON DELETE SET NULL
);
CREATE UNIQUE INDEX BUSINCOME_INDEX_IID ON BUS_INCOME (IID ASC);
CREATE TABLE BUS_REMIND (
RID varchar(36) PRIMARY KEY NOT NULL,
REMARK nvarchar(36) NOT NULL,
RTYPE integer(2) NOT NULL DEFAULT(0),
RTIME varchar,
STATUS integer(2) NOT NULL DEFAULT(0),
RDAY integer(2)
);
CREATE UNIQUE INDEX BUSREMIND_INDEX_RID ON BUS_REMIND (RID ASC);
CREATE TABLE BASE_PACKAGE (
PID varchar(36) PRIMARY KEY NOT NULL,
PNAME nvarchar(16) NOT NULL,
PVALUE double NOT NULL DEFAULT(0),
PCOLOR varchar(10),
PORDER integer(4) NOT NULL DEFAULT(0),
ISVALID integer(2) NOT NULL DEFAULT(1)
);
CREATE UNIQUE INDEX BASEPACKAGE_INDEX_PID ON BASE_PACKAGE (PID ASC);
CREATE TABLE BUS_TRANSFER (
ID varchar(36) PRIMARY KEY NOT NULL,
FROMPID varchar(36) NOT NULL,
TOPID varchar(36) NOT NULL,
TVALUE double NOT NULL,
ISVALID integer(2) DEFAULT(0)
);
CREATE UNIQUE INDEX BUSTRANSFER_INDEX_ID ON BUS_TRANSFER (ID ASC);
CREATE TABLE BASE_THEMES (
TID varchar(36) PRIMARY KEY NOT NULL,
TNAME nvarchar(15) NOT NULL,
ISVALID integer(1) NOT NULL DEFAULT(1),
"TIMESTAMP" varchar(128) NOT NULL
);
CREATE TABLE BASE_THEMESDETAIL (
TID varchar(36) NOT NULL,
DID varchar(36) PRIMARY KEY NOT NULL,
DNAME nvarchar(36) NOT NULL,
DTHUMB varchar(36) NOT NULL,
DSOURCE varchar(36) NOT NULL,
ISVALID integer(1) NOT NULL DEFAULT(1),
"TIMESTAMP" varchar(128) NOT NULL,
FOREIGN KEY (TID) REFERENCES BASE_THEMES (TID) ON DELETE SET NULL
);